// Mocks generated by Mockito 5.4.4 from annotations
// in finance_house_task/test/new_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:finance_house_task/model/movie/movie.dart' as _i4;
import 'package:finance_house_task/model/movie/trailer.dart' as _i5;
import 'package:finance_house_task/service/movie_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieService extends _i1.Mock implements _i2.MovieService {
  MockMovieService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> getPopularMovies({int? pageNo = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
          {#pageNo: pageNo},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> getNowPlaying({int? pageNo = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlaying,
          [],
          {#pageNo: pageNo},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  Map<String, dynamic> parsedObj(Map<String, dynamic>? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #parsedObj,
          [response],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<Map<String, dynamic>?> getTopRated({int? pageNo = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRated,
          [],
          {#pageNo: pageNo},
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<_i4.Movie?> getMovieDetails({
    required int? movieId,
    String? appendToRes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [],
          {
            #movieId: movieId,
            #appendToRes: appendToRes,
          },
        ),
        returnValue: _i3.Future<_i4.Movie?>.value(),
      ) as _i3.Future<_i4.Movie?>);

  @override
  _i3.Future<Map<String, dynamic>?> getSearchedMovie({
    int? pageNo = 1,
    String? query = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSearchedMovie,
          [],
          {
            #pageNo: pageNo,
            #query: query,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<_i5.Trailer>?> getTrailer({
    required int? movieId,
    String? appendToRes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrailer,
          [],
          {
            #movieId: movieId,
            #appendToRes: appendToRes,
          },
        ),
        returnValue: _i3.Future<List<_i5.Trailer>?>.value(),
      ) as _i3.Future<List<_i5.Trailer>?>);

  @override
  _i3.Future<Map<String, dynamic>?> get(
    String? url, {
    Map<String, String?>? params = null,
    bool? useAuthHeaders = true,
    Map<String, String?>? customHeader,
    dynamic useBaseUrl = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {
            #params: params,
            #useAuthHeaders: useAuthHeaders,
            #customHeader: customHeader,
            #useBaseUrl: useBaseUrl,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> post(
    String? url, {
    required Map<String, dynamic>? body,
    bool? useAuthHeaders = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #body: body,
            #useAuthHeaders: useAuthHeaders,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> put(
    String? url, {
    required Map<String, String>? body,
    bool? useAuthHeaders = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #body: body,
            #useAuthHeaders: useAuthHeaders,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> patch(
    String? url, {
    required Map<String, dynamic>? body,
    bool? useAuthHeaders = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #body: body,
            #useAuthHeaders: useAuthHeaders,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> delete(
    String? url, {
    Map<String, String>? params,
    bool? useAuthHeaders = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #params: params,
            #useAuthHeaders: useAuthHeaders,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
}
