// Mocks generated by Mockito 5.4.4 from annotations
// in finance_house_task/test/mocks/favorites_service.fake.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:finance_house_task/model/movie/movie.dart' as _i4;
import 'package:finance_house_task/service/fav_movie_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavMovieService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavMovieService extends _i1.Mock implements _i2.FavMovieService {
  MockFavMovieService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Movie>> getAllFavMovie() => (super.noSuchMethod(
        Invocation.method(
          #getAllFavMovie,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Movie>>.value(<_i4.Movie>[]),
      ) as _i3.Future<List<_i4.Movie>>);

  @override
  _i3.Future<void> removeFavMovie(_i4.Movie? movie) => (super.noSuchMethod(
        Invocation.method(
          #removeFavMovie,
          [movie],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addFavMovie({_i4.Movie? movie}) => (super.noSuchMethod(
        Invocation.method(
          #addFavMovie,
          [],
          {#movie: movie},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
